### NUMPY PRACTICE QUESTIONS

#### 1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

In [7]:
import numpy as np

# Define custom numpy arrays A and B
A = np.array([[1, 2, 3], [4, 5, 6]])

B = np.array([[7, 4, 9], [10, 11, 2]])

# Stack A and B vertically
stacked_vertically = np.vstack((A, B))

# Stack A and B horizontally
stacked_horizontally = np.hstack((A, B))

print("Stacked vertically:\n", stacked_vertically)
print("Stacked horizontally:\n", stacked_horizontally)


Stacked vertically:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  4  9]
 [10 11  2]]
Stacked horizontally:
 [[ 1  2  3  7  4  9]
 [ 4  5  6 10 11  2]]


#### 2. Find common elements between A and B. [Hint : Intersection of two sets]

In [16]:
common_elements = np.intersect1d(A, B)

print("Common elements between A and B:", common_elements)

Common elements between A and B: [2 4]


#### 3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

In [18]:
# Use np.where() to find elements within the range
elements_in_range = A[np.where((A >= 5) & (A <= 10))]

print("Elements within the range [5, 10] in array A:")
print(elements_in_range)

Elements within the range [5, 10] in array A:
[5 6]


#### 4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
	url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
	iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [22]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

iris_2d

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [21]:
# Filtering for 3rd column > 1.5 and 1st column < 5.0
condition = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)

# Use the boolean mask to filter the rows
filtered_rows = iris_2d[condition]

print("Filtered rows of iris_2d:")
print(filtered_rows)

Filtered rows of iris_2d:
[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


### PANDAS PRACTICE QUESTIONS

#### 1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

In [24]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small       12.9   15.9       18.8      25.0   
1           NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2          Audi       90  Compact       25.9   29.1       32.3      20.0   
3          Audi      100  Midsize        NaN   37.7       44.6      19.0   
4           BMW     535i  Midsize        NaN   30.0        NaN      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van       16.6   19.7       22.7      17.0   
89   Volkswagen   Passat  Compact       17.6   20.0       22.4      21.0   
90   Volkswagen  Corrado   Sporty       22.9   23.3       23.7      18.0   
91        Volvo      240  Compact       21.8   22.7       23.5      21.0   
92          NaN      850  Midsize       24.8   26.7       28.5      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                 NaN      Front  ...        5.0   177.0   
1          25.0  Driver & Passenger      Front  ...        5.0   195.0   
2          26.0         Driver only      Front  ...        5.0   180.0   
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4          30.0                 NaN       Rear  ...        4.0   186.0   
..          ...                 ...        ...  ...        ...     ...   
88         21.0                 NaN      Front  ...        7.0   187.0   
89         30.0                 NaN      Front  ...        5.0   180.0   
90         25.0                 NaN      Front  ...        4.0   159.0   
91         28.0         Driver only       Rear  ...        5.0   190.0   
92         28.0  Driver & Passenger      Front  ...        5.0   184.0   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0   
1       115.0   71.0         38.0           30.0          15.0  3560.0   
2       102.0   67.0         37.0           28.0          14.0  3375.0   
3       106.0    NaN         37.0           31.0          17.0  3405.0   
4       109.0   69.0         39.0           27.0          13.0  3640.0   
..        ...    ...          ...            ...           ...     ...   
88      115.0   72.0         38.0           34.0           NaN  3960.0   
89      103.0   67.0         35.0           31.5          14.0  2985.0   
90       97.0   66.0         36.0           26.0          15.0  2810.0   
91      104.0   67.0         37.0           29.5          14.0  2985.0   
92      105.0   69.0         38.0           30.0          15.0  3245.0   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88      NaN  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 27 columns]

In [28]:
filtered_df = df.iloc[::20, [0, 1, 2]]

print(filtered_df)

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


#### 2. Replace missing values in Min.Price and Max.Price columns with their respective mean.

In [31]:
# Replace NaN values in 'Min.Price' with the mean of 'Min.Price'
df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)

# Replace NaN values in 'Max.Price' with the mean of 'Max.Price'
df['Max.Price'].fillna(df['Max.Price'].mean(), inplace=True)

df

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small  12.900000   15.9  18.800000      25.0   
1           NaN   Legend  Midsize  29.200000   33.9  38.700000      18.0   
2          Audi       90  Compact  25.900000   29.1  32.300000      20.0   
3          Audi      100  Midsize  17.118605   37.7  44.600000      19.0   
4           BMW     535i  Midsize  17.118605   30.0  21.459091      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van  16.600000   19.7  22.700000      17.0   
89   Volkswagen   Passat  Compact  17.600000   20.0  22.400000      21.0   
90   Volkswagen  Corrado   Sporty  22.900000   23.3  23.700000      18.0   
91        Volvo      240  Compact  21.800000   22.7  23.500000      21.0   
92          NaN      850  Midsize  24.800000   26.7  28.500000      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                 NaN      Front  ...        5.0   177.0   
1          25.0  Driver & Passenger      Front  ...        5.0   195.0   
2          26.0         Driver only      Front  ...        5.0   180.0   
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4          30.0                 NaN       Rear  ...        4.0   186.0   
..          ...                 ...        ...  ...        ...     ...   
88         21.0                 NaN      Front  ...        7.0   187.0   
89         30.0                 NaN      Front  ...        5.0   180.0   
90         25.0                 NaN      Front  ...        4.0   159.0   
91         28.0         Driver only       Rear  ...        5.0   190.0   
92         28.0  Driver & Passenger      Front  ...        5.0   184.0   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0   
1       115.0   71.0         38.0           30.0          15.0  3560.0   
2       102.0   67.0         37.0           28.0          14.0  3375.0   
3       106.0    NaN         37.0           31.0          17.0  3405.0   
4       109.0   69.0         39.0           27.0          13.0  3640.0   
..        ...    ...          ...            ...           ...     ...   
88      115.0   72.0         38.0           34.0           NaN  3960.0   
89      103.0   67.0         35.0           31.5          14.0  2985.0   
90       97.0   66.0         36.0           26.0          15.0  2810.0   
91      104.0   67.0         37.0           29.5          14.0  2985.0   
92      105.0   69.0         38.0           30.0          15.0  3245.0   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88      NaN  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 27 columns]

#### 3. How to get the rows of a dataframe with row sum > 100?

In [33]:
df_2 = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

df_2

0   1   2   3
0   37  32  39  22
1   15  28  39  26
2   10  39  10  14
3   23  33  38  37
4   12  20  38  31
5   28  34  29  39
6   17  15  21  27
7   25  23  18  31
8   29  31  15  27
9   28  31  23  21
10  38  14  22  38
11  29  22  31  20
12  24  13  34  19
13  12  30  31  24
14  26  15  24  25

In [44]:
sum_rows = df_2.sum(axis=1)
sum_rows

0     130
1     108
2      73
3     131
4     101
5     130
6      80
7      97
8     102
9     103
10    112
11    102
12     90
13     97
14     90
dtype: int64

In [45]:
sum_greater_100 = df_2[sum_rows > 100]
print(sum_greater_100)

     0   1   2   3
0   37  32  39  22
1   15  28  39  26
3   23  33  38  37
4   12  20  38  31
5   28  34  29  39
8   29  31  15  27
9   28  31  23  21
10  38  14  22  38
11  29  22  31  20
